version: "3.9"
services:
  web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.usecase1-3-web.rule=Host(`${FRONTEND_DOMAIN}`)"
      - "traefik.http.routers.risk_management-api.entrypoints=websecure"
      - "traefik.http.routers.risk_management-api.tls=true"
    env_file:
      - .env-web.development
  api:
    labels:
      - traefik.enable=true
      - traefik.http.routers.usecase1-3-api.rule=Host(`${BACKEND_DOMAIN}`)
      - "traefik.http.routers.risk_management-api.entrypoints=websecure"
      - "traefik.http.routers.risk_management-api.tls=true"
