version: '3.9'
services:
  dataabase:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongodb:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD","mongo","--quiet","127.0.0.1/test","--eval","'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  cache:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  web:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      cache:
        condition: service_healthy
  api:
    build:
      context: ./ProductApi
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    depends_on:
      dataabase:
        condition: service_healthy
  