version: '3.9'
services:
  database:
    image: mongo:4.2
    volumes:
      - "./data/mongodb:/data/db"    
    restart: on-failure:2
    healthcheck:
      test: ["CMD","mongo","--quiet","127.0.0.1/test","--eval","'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  cache:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  web:
    image: nginx
  api:
    build:
      context: ./ProductApi
      dockerfile: Dockerfile    
    depends_on:
      database:
        condition: service_healthy
  