version: "3.9"
services:
  reverse-proxy:
    image: traefik:v2.9.5
    container_name: traefik
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  whoami:
    image: traefik/whoami
    deploy:
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.risk_management-whoami.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.routers.risk_management-whoami.entrypoints=web"